# Generated by Django 4.1.2 on 2022-10-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_alter_tarea_fechacumplida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fechacumplida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
